
-- ==========================================
-- CLEAR ALL CRM DATA
-- ==========================================
-- WARNING: This will permanently delete ALL customers, leads, projects, tickets, and services!

TRUNCATE TABLE public.tickets CASCADE;
TRUNCATE TABLE public.projects CASCADE;
TRUNCATE TABLE public.leads CASCADE;
TRUNCATE TABLE public.sales CASCADE;
TRUNCATE TABLE public.customers CASCADE;
TRUNCATE TABLE public.services CASCADE;

-- Optionally, delete the demo users generated by the seed script
DELETE FROM auth.users WHERE email LIKE '%@example.com';
