/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets.$ticketId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'
import { Route as AuthenticatedCrmCustomerIdRouteImport } from './routes/_authenticated/crm.$customerId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmCustomerIdRoute =
  AuthenticatedCrmCustomerIdRouteImport.update({
    id: '/crm/$customerId',
    path: '/crm/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr': typeof AuthenticatedHrRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/crm/$customerId': typeof AuthenticatedCrmCustomerIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr': typeof AuthenticatedHrRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/crm/$customerId': typeof AuthenticatedCrmCustomerIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/crm/$customerId': typeof AuthenticatedCrmCustomerIdRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/hr'
    | '/reports'
    | '/settings'
    | '/crm/$customerId'
    | '/leads/$leadId'
    | '/projects/$projectId'
    | '/tickets/$ticketId'
    | '/crm/'
    | '/leads/'
    | '/projects/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/hr'
    | '/reports'
    | '/settings'
    | '/crm/$customerId'
    | '/leads/$leadId'
    | '/projects/$projectId'
    | '/tickets/$ticketId'
    | '/crm'
    | '/leads'
    | '/projects'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/hr'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/crm/$customerId'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/tickets/$ticketId'
    | '/_authenticated/crm/'
    | '/_authenticated/leads/'
    | '/_authenticated/projects/'
    | '/_authenticated/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/$ticketId': {
      id: '/_authenticated/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/$customerId': {
      id: '/_authenticated/crm/$customerId'
      path: '/crm/$customerId'
      fullPath: '/crm/$customerId'
      preLoaderRoute: typeof AuthenticatedCrmCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCrmCustomerIdRoute: typeof AuthenticatedCrmCustomerIdRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCrmCustomerIdRoute: AuthenticatedCrmCustomerIdRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
